### ISSUE TITLE
License

### ISSUE THREAD

**Issue by notpushkin** [Dante-Leoncini/Whisk3D#2]
Hey, first of all thanks for your wonderful project!

I've noticed this repo lacks a LICENSE file, which is the usual way of specifying the project's license. This means the project is [not licensed / non-open source](https://choosealicense.com/no-permission/), and people can't use it legally. Could you [pick a license](https://choosealicense.com/) and add it to the repo? Let me know if you need any help with that!

**Comment by Dante-Leoncini** [comment]
I've already added an MIT license
